import type { CardDefinition } from '../types/cards';

export const CHAOS_CARDS: CardDefinition[] = [
  {
    id: 'transfer-ban',
    type: 'chaos',
    name: 'Transfer Ban',
    description: 'Target cannot bid on the next 2 auction rounds.',
    flavor: 'Transfer ban imposed. Sit this one out.',
    color: '#FF4444',
    icon: '🚫',
    targetType: 'random',
  },
  {
    id: 'injury-concern',
    type: 'chaos',
    name: 'Injury Concern',
    description: "Target's most recently purchased player is removed. CP not refunded.",
    flavor: 'Injury in training. That player won\'t be available.',
    color: '#FF6B35',
    icon: '🤕',
    targetType: 'random',
  },
  {
    id: 'ego-clash',
    type: 'chaos',
    name: 'Ego Clash',
    description: "Target's highest-rated player is removed and re-entered into the auction. CP is refunded.",
    flavor: 'Dressing room revolt. Your star has handed in a transfer request.',
    color: '#FF4444',
    icon: '💥',
    targetType: 'random',
  },
  {
    id: 'blind-bag',
    type: 'chaos',
    name: 'Blind Bag',
    description: 'System picks 1 random player from the remaining pool and gives it for free.',
    flavor: 'Lucky dip! Could be a world-beater... or a disaster.',
    color: '#9B59B6',
    icon: '🎁',
    targetType: 'random',
  },
  {
    id: 'the-swap',
    type: 'chaos',
    name: 'The Swap',
    description: "Two random players' entire remaining CP budgets are swapped.",
    flavor: 'Power shift. Fortunes reversed.',
    color: '#3498DB',
    icon: '🔄',
    targetType: 'two-random',
  },
  {
    id: 'double-down',
    type: 'chaos',
    name: 'Double Down',
    description: 'The starting bid for the very next player auctioned is double their base CP value.',
    flavor: 'High stakes. The market is heating up.',
    color: '#E67E22',
    icon: '⚡',
    targetType: 'all',
  },
  {
    id: 'time-bomb',
    type: 'chaos',
    name: 'Time Bomb',
    description: 'The next bidding round runs on a 4-second timer instead of normal.',
    flavor: 'Panic buy. Think fast.',
    color: '#FF4444',
    icon: '💣',
    targetType: 'all',
  },
  {
    id: 'position-reroll',
    type: 'chaos',
    name: 'Position Reroll',
    description: 'System re-spins the position wheel, discarding the current result.',
    flavor: 'Change of plans. The position has been redrawn.',
    color: '#1ABC9C',
    icon: '🎯',
    targetType: 'all',
  },
];

export const FINANCE_CARDS: CardDefinition[] = [
  {
    id: 'oil-money',
    type: 'finance',
    name: 'Oil Money Takeover',
    description: '+25 CP added to target\'s budget instantly.',
    flavor: 'A mysterious consortium has purchased your club!',
    color: '#FFD700',
    icon: '🛢️',
    targetType: 'random',
    weightedTarget: { type: 'richest', weight: 0.4 },
  },
  {
    id: 'ffp-violation',
    type: 'finance',
    name: 'FFP Violation',
    description: '-15 CP deducted from target\'s budget (minimum 0).',
    flavor: 'UEFA has opened a Financial Fair Play investigation against you.',
    color: '#FF4444',
    icon: '⚖️',
    targetType: 'random',
    weightedTarget: { type: 'richest', weight: 0.6 },
  },
  {
    id: 'bankruptcy-bailout',
    type: 'finance',
    name: 'Bankruptcy Bailout',
    description: '+20 CP to the player with the lowest budget.',
    flavor: "Emergency funds approved. You've been saved — for now.",
    color: '#2ECC71',
    icon: '🏦',
    targetType: 'poorest',
  },
  {
    id: 'tax-raid',
    type: 'finance',
    name: 'Tax Raid',
    description: '-10 CP from the richest player, redistributed equally to all others.',
    flavor: 'The tax authorities have come knocking.',
    color: '#E74C3C',
    icon: '🏛️',
    targetType: 'richest',
  },
  {
    id: 'prize-windfall',
    type: 'finance',
    name: 'Prize Money Windfall',
    description: '+8 CP to every player.',
    flavor: 'Record-breaking TV rights deal announced. Everyone benefits.',
    color: '#F39C12',
    icon: '📺',
    targetType: 'all',
  },
  {
    id: 'wage-bill-crisis',
    type: 'finance',
    name: 'Wage Bill Crisis',
    description: '-5 CP per player owned (min -5, max -20).',
    flavor: 'Your wage bill is out of control. Time to cut costs.',
    color: '#E74C3C',
    icon: '💸',
    targetType: 'random',
  },
];

export const ALL_CARDS = [...CHAOS_CARDS, ...FINANCE_CARDS];
