import type { Player } from '../types/player';
import { getBaseValue } from '../types/player';

// Helper to build sofifa image URL (fallback to generated avatar)
function sfImg(sofifaId: number): string {
  return `https://cdn.sofifa.net/players/${Math.floor(sofifaId / 1000)}/${sofifaId % 1000}/25_120.png`;
}

function flag(countryCode: string): string {
  return `https://flagcdn.com/w40/${countryCode.toLowerCase()}.png`;
}

function badge(clubSlug: string): string {
  // Use a public badge CDN — fallback handled in UI
  return `https://media.api-sports.io/football/teams/${clubSlug}.png`;
}

const ALL_EDITIONS = ['world-cup', 'champions-league', 'premier-league', 'la-liga', 'bundesliga', 'all-time-legends', 'custom'];
const PL_EDITIONS = ['premier-league', 'custom'];
const UCL_MODERN = ['champions-league', 'world-cup', 'custom'];
const LIGA_EDITIONS = ['la-liga', 'champions-league', 'custom'];
const BUND_EDITIONS = ['bundesliga', 'champions-league', 'custom'];
const LEGEND_EDITIONS = ['all-time-legends', 'custom'];
const WC_ONLY = ['world-cup', 'custom'];

export const PLAYERS: Player[] = [
  // ========================================
  // ICON / TOTY (Rating 95+) — 15 players
  // ========================================
  {
    id: 'messi',
    name: 'Lionel Messi',
    shortName: 'L. Messi',
    position: 'RW',
    rating: 98,
    pace: 86,
    shooting: 95,
    passing: 97,
    dribbling: 99,
    defending: 38,
    physical: 65,
    nationality: 'AR',
    nationalityFull: 'Argentina',
    club: 'Inter Miami CF',
    league: 'MLS',
    imageUrl: sfImg(158023),
    flagUrl: flag('ar'),
    clubBadgeUrl: badge('10714'),
    baseValue: getBaseValue(98),
    editions: [...LEGEND_EDITIONS, 'world-cup', 'custom'],
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'ronaldo',
    name: 'Cristiano Ronaldo',
    shortName: 'C. Ronaldo',
    position: 'ST',
    rating: 97,
    pace: 83,
    shooting: 96,
    passing: 82,
    dribbling: 92,
    defending: 35,
    physical: 82,
    nationality: 'PT',
    nationalityFull: 'Portugal',
    club: 'Al Nassr',
    league: 'Saudi Pro League',
    imageUrl: sfImg(20801),
    flagUrl: flag('pt'),
    clubBadgeUrl: badge('2932'),
    baseValue: getBaseValue(97),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'zidane',
    name: 'Zinedine Zidane',
    shortName: 'Zidane',
    position: 'CAM',
    rating: 97,
    pace: 76,
    shooting: 83,
    passing: 96,
    dribbling: 97,
    defending: 54,
    physical: 78,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(12),
    flagUrl: flag('fr'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(97),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'ronaldinho',
    name: 'Ronaldinho',
    shortName: 'Ronaldinho',
    position: 'CAM',
    rating: 96,
    pace: 81,
    shooting: 88,
    passing: 91,
    dribbling: 98,
    defending: 30,
    physical: 72,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(30),
    flagUrl: flag('br'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(96),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'pele',
    name: 'Pelé',
    shortName: 'Pelé',
    position: 'ST',
    rating: 98,
    pace: 92,
    shooting: 97,
    passing: 88,
    dribbling: 96,
    defending: 33,
    physical: 80,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(1),
    flagUrl: flag('br'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(98),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'maradona',
    name: 'Diego Maradona',
    shortName: 'Maradona',
    position: 'CAM',
    rating: 97,
    pace: 88,
    shooting: 87,
    passing: 90,
    dribbling: 99,
    defending: 42,
    physical: 75,
    nationality: 'AR',
    nationalityFull: 'Argentina',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(2),
    flagUrl: flag('ar'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(97),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'beckenbauer',
    name: 'Franz Beckenbauer',
    shortName: 'Beckenbauer',
    position: 'CB',
    rating: 95,
    pace: 75,
    shooting: 65,
    passing: 85,
    dribbling: 80,
    defending: 96,
    physical: 82,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(3),
    flagUrl: flag('de'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(95),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'van-basten',
    name: 'Marco van Basten',
    shortName: 'Van Basten',
    position: 'ST',
    rating: 96,
    pace: 83,
    shooting: 97,
    passing: 78,
    dribbling: 90,
    defending: 30,
    physical: 83,
    nationality: 'NL',
    nationalityFull: 'Netherlands',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(4),
    flagUrl: flag('nl'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(96),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'cruyff',
    name: 'Johan Cruyff',
    shortName: 'Cruyff',
    position: 'ST',
    rating: 95,
    pace: 90,
    shooting: 88,
    passing: 91,
    dribbling: 97,
    defending: 40,
    physical: 72,
    nationality: 'NL',
    nationalityFull: 'Netherlands',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(5),
    flagUrl: flag('nl'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(95),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'maldini',
    name: 'Paolo Maldini',
    shortName: 'Maldini',
    position: 'LB',
    rating: 96,
    pace: 82,
    shooting: 58,
    passing: 79,
    dribbling: 80,
    defending: 97,
    physical: 85,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(6),
    flagUrl: flag('it'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(96),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'buffon',
    name: 'Gianluigi Buffon',
    shortName: 'Buffon',
    position: 'GK',
    rating: 95,
    pace: 50,
    shooting: 15,
    passing: 52,
    dribbling: 18,
    defending: 20,
    physical: 78,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(30578),
    flagUrl: flag('it'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(95),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'henry',
    name: 'Thierry Henry',
    shortName: 'T. Henry',
    position: 'ST',
    rating: 96,
    pace: 95,
    shooting: 93,
    passing: 78,
    dribbling: 95,
    defending: 35,
    physical: 79,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(7),
    flagUrl: flag('fr'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(96),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'xavi',
    name: 'Xavi Hernández',
    shortName: 'Xavi',
    position: 'CM',
    rating: 95,
    pace: 78,
    shooting: 76,
    passing: 97,
    dribbling: 91,
    defending: 72,
    physical: 70,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(41523),
    flagUrl: flag('es'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(95),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'iniesta',
    name: 'Andrés Iniesta',
    shortName: 'Iniesta',
    position: 'CM',
    rating: 95,
    pace: 79,
    shooting: 79,
    passing: 95,
    dribbling: 96,
    defending: 65,
    physical: 68,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(41726),
    flagUrl: flag('es'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(95),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'pirlo',
    name: 'Andrea Pirlo',
    shortName: 'Pirlo',
    position: 'CDM',
    rating: 95,
    pace: 58,
    shooting: 80,
    passing: 96,
    dribbling: 82,
    defending: 77,
    physical: 72,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(31921),
    flagUrl: flag('it'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(95),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },

  // ========================================
  // SPECIAL (Rating 90–94) — 25 players
  // ========================================
  {
    id: 'mbappe',
    name: 'Kylian Mbappé',
    shortName: 'Mbappé',
    position: 'ST',
    rating: 94,
    pace: 98,
    shooting: 93,
    passing: 83,
    dribbling: 94,
    defending: 37,
    physical: 78,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(231747),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(94),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'haaland',
    name: 'Erling Haaland',
    shortName: 'Haaland',
    position: 'ST',
    rating: 94,
    pace: 94,
    shooting: 95,
    passing: 72,
    dribbling: 84,
    defending: 45,
    physical: 90,
    nationality: 'NO',
    nationalityFull: 'Norway',
    club: 'Manchester City',
    league: 'Premier League',
    imageUrl: sfImg(239085),
    flagUrl: flag('no'),
    clubBadgeUrl: badge('50'),
    baseValue: getBaseValue(94),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'vinicius',
    name: 'Vinícius Jr.',
    shortName: 'Vinícius Jr.',
    position: 'LW',
    rating: 92,
    pace: 97,
    shooting: 88,
    passing: 80,
    dribbling: 95,
    defending: 28,
    physical: 74,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(238794),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(92),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'bellingham',
    name: 'Jude Bellingham',
    shortName: 'Bellingham',
    position: 'CM',
    rating: 92,
    pace: 82,
    shooting: 87,
    passing: 87,
    dribbling: 91,
    defending: 75,
    physical: 85,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(237692),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(92),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'salah',
    name: 'Mohamed Salah',
    shortName: 'M. Salah',
    position: 'RW',
    rating: 91,
    pace: 93,
    shooting: 90,
    passing: 84,
    dribbling: 92,
    defending: 44,
    physical: 74,
    nationality: 'EG',
    nationalityFull: 'Egypt',
    club: 'Liverpool',
    league: 'Premier League',
    imageUrl: sfImg(209331),
    flagUrl: flag('eg'),
    clubBadgeUrl: badge('40'),
    baseValue: getBaseValue(91),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'de-bruyne',
    name: 'Kevin De Bruyne',
    shortName: 'De Bruyne',
    position: 'CM',
    rating: 91,
    pace: 76,
    shooting: 86,
    passing: 95,
    dribbling: 88,
    defending: 63,
    physical: 78,
    nationality: 'BE',
    nationalityFull: 'Belgium',
    club: 'Manchester City',
    league: 'Premier League',
    imageUrl: sfImg(192985),
    flagUrl: flag('be'),
    clubBadgeUrl: badge('50'),
    baseValue: getBaseValue(91),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'alisson',
    name: 'Alisson Becker',
    shortName: 'Alisson',
    position: 'GK',
    rating: 91,
    pace: 62,
    shooting: 18,
    passing: 73,
    dribbling: 25,
    defending: 22,
    physical: 84,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Liverpool',
    league: 'Premier League',
    imageUrl: sfImg(212831),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('40'),
    baseValue: getBaseValue(91),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'ruben-dias',
    name: 'Rúben Dias',
    shortName: 'R. Dias',
    position: 'CB',
    rating: 90,
    pace: 77,
    shooting: 41,
    passing: 72,
    dribbling: 63,
    defending: 92,
    physical: 87,
    nationality: 'PT',
    nationalityFull: 'Portugal',
    club: 'Manchester City',
    league: 'Premier League',
    imageUrl: sfImg(239477),
    flagUrl: flag('pt'),
    clubBadgeUrl: badge('50'),
    baseValue: getBaseValue(90),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'lamine-yamal',
    name: 'Lamine Yamal',
    shortName: 'L. Yamal',
    position: 'RW',
    rating: 91,
    pace: 95,
    shooting: 85,
    passing: 87,
    dribbling: 95,
    defending: 26,
    physical: 60,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'FC Barcelona',
    league: 'La Liga',
    imageUrl: sfImg(278971),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('529'),
    baseValue: getBaseValue(91),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'pedri',
    name: 'Pedri',
    shortName: 'Pedri',
    position: 'CM',
    rating: 90,
    pace: 78,
    shooting: 80,
    passing: 89,
    dribbling: 92,
    defending: 68,
    physical: 64,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'FC Barcelona',
    league: 'La Liga',
    imageUrl: sfImg(270726),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('529'),
    baseValue: getBaseValue(90),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'kroos',
    name: 'Toni Kroos',
    shortName: 'T. Kroos',
    position: 'CM',
    rating: 91,
    pace: 54,
    shooting: 82,
    passing: 96,
    dribbling: 82,
    defending: 78,
    physical: 74,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(182521),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(91),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'lewandowski',
    name: 'Robert Lewandowski',
    shortName: 'Lewandowski',
    position: 'ST',
    rating: 90,
    pace: 81,
    shooting: 95,
    passing: 78,
    dribbling: 84,
    defending: 43,
    physical: 82,
    nationality: 'PL',
    nationalityFull: 'Poland',
    club: 'FC Barcelona',
    league: 'La Liga',
    imageUrl: sfImg(188545),
    flagUrl: flag('pl'),
    clubBadgeUrl: badge('529'),
    baseValue: getBaseValue(90),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'ter-stegen',
    name: 'Marc-André ter Stegen',
    shortName: 'Ter Stegen',
    position: 'GK',
    rating: 90,
    pace: 58,
    shooting: 19,
    passing: 72,
    dribbling: 25,
    defending: 19,
    physical: 79,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'FC Barcelona',
    league: 'La Liga',
    imageUrl: sfImg(191511),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('529'),
    baseValue: getBaseValue(90),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'van-dijk',
    name: 'Virgil van Dijk',
    shortName: 'Van Dijk',
    position: 'CB',
    rating: 90,
    pace: 82,
    shooting: 60,
    passing: 71,
    dribbling: 72,
    defending: 93,
    physical: 90,
    nationality: 'NL',
    nationalityFull: 'Netherlands',
    club: 'Liverpool',
    league: 'Premier League',
    imageUrl: sfImg(203376),
    flagUrl: flag('nl'),
    clubBadgeUrl: badge('40'),
    baseValue: getBaseValue(90),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'rodri',
    name: 'Rodri',
    shortName: 'Rodri',
    position: 'CDM',
    rating: 92,
    pace: 73,
    shooting: 75,
    passing: 90,
    dribbling: 82,
    defending: 91,
    physical: 84,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Manchester City',
    league: 'Premier League',
    imageUrl: sfImg(231866),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('50'),
    baseValue: getBaseValue(92),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'son',
    name: 'Heung-Min Son',
    shortName: 'Son',
    position: 'LW',
    rating: 90,
    pace: 90,
    shooting: 88,
    passing: 82,
    dribbling: 88,
    defending: 48,
    physical: 73,
    nationality: 'KR',
    nationalityFull: 'South Korea',
    club: 'Tottenham',
    league: 'Premier League',
    imageUrl: sfImg(202252),
    flagUrl: flag('kr'),
    clubBadgeUrl: badge('47'),
    baseValue: getBaseValue(90),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'saka',
    name: 'Bukayo Saka',
    shortName: 'Saka',
    position: 'RW',
    rating: 90,
    pace: 88,
    shooting: 83,
    passing: 85,
    dribbling: 90,
    defending: 57,
    physical: 68,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Arsenal',
    league: 'Premier League',
    imageUrl: sfImg(246669),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('42'),
    baseValue: getBaseValue(90),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'rashford',
    name: 'Marcus Rashford',
    shortName: 'Rashford',
    position: 'LW',
    rating: 90,
    pace: 92,
    shooting: 86,
    passing: 77,
    dribbling: 89,
    defending: 43,
    physical: 77,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Manchester United',
    league: 'Premier League',
    imageUrl: sfImg(231678),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('33'),
    baseValue: getBaseValue(90),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'osimhen',
    name: 'Victor Osimhen',
    shortName: 'Osimhen',
    position: 'ST',
    rating: 90,
    pace: 95,
    shooting: 88,
    passing: 65,
    dribbling: 82,
    defending: 38,
    physical: 85,
    nationality: 'NG',
    nationalityFull: 'Nigeria',
    club: 'Galatasaray',
    league: 'Süper Lig',
    imageUrl: sfImg(246983),
    flagUrl: flag('ng'),
    clubBadgeUrl: badge('645'),
    baseValue: getBaseValue(90),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'camavinga',
    name: 'Eduardo Camavinga',
    shortName: 'Camavinga',
    position: 'CM',
    rating: 90,
    pace: 85,
    shooting: 74,
    passing: 83,
    dribbling: 88,
    defending: 83,
    physical: 80,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(261657),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(90),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'gavi',
    name: 'Gavi',
    shortName: 'Gavi',
    position: 'CM',
    rating: 90,
    pace: 74,
    shooting: 76,
    passing: 87,
    dribbling: 90,
    defending: 78,
    physical: 65,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'FC Barcelona',
    league: 'La Liga',
    imageUrl: sfImg(262133),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('529'),
    baseValue: getBaseValue(90),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'theo-hernandez',
    name: 'Théo Hernández',
    shortName: 'T. Hernández',
    position: 'LB',
    rating: 90,
    pace: 93,
    shooting: 79,
    passing: 76,
    dribbling: 85,
    defending: 82,
    physical: 83,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'AC Milan',
    league: 'Serie A',
    imageUrl: sfImg(238679),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('489'),
    baseValue: getBaseValue(90),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'leao',
    name: 'Rafael Leão',
    shortName: 'R. Leão',
    position: 'LW',
    rating: 90,
    pace: 96,
    shooting: 85,
    passing: 78,
    dribbling: 93,
    defending: 33,
    physical: 72,
    nationality: 'PT',
    nationalityFull: 'Portugal',
    club: 'AC Milan',
    league: 'Serie A',
    imageUrl: sfImg(244839),
    flagUrl: flag('pt'),
    clubBadgeUrl: badge('489'),
    baseValue: getBaseValue(90),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'diogo-jota',
    name: 'Diogo Jota',
    shortName: 'D. Jota',
    position: 'ST',
    rating: 90,
    pace: 88,
    shooting: 87,
    passing: 76,
    dribbling: 86,
    defending: 44,
    physical: 73,
    nationality: 'PT',
    nationalityFull: 'Portugal',
    club: 'Liverpool',
    league: 'Premier League',
    imageUrl: sfImg(222351),
    flagUrl: flag('pt'),
    clubBadgeUrl: badge('40'),
    baseValue: getBaseValue(90),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'robertson',
    name: 'Andrew Robertson',
    shortName: 'Robertson',
    position: 'LB',
    rating: 90,
    pace: 87,
    shooting: 65,
    passing: 83,
    dribbling: 77,
    defending: 88,
    physical: 77,
    nationality: 'GB-SCT',
    nationalityFull: 'Scotland',
    club: 'Liverpool',
    league: 'Premier League',
    imageUrl: sfImg(219716),
    flagUrl: flag('gb-sct'),
    clubBadgeUrl: badge('40'),
    baseValue: getBaseValue(90),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },

  // ========================================
  // RARE GOLD (Rating 85–89) — 60 players
  // ========================================
  {
    id: 'trent',
    name: 'Trent Alexander-Arnold',
    shortName: 'Alexander-Arnold',
    position: 'RB',
    rating: 89,
    pace: 79,
    shooting: 77,
    passing: 93,
    dribbling: 79,
    defending: 79,
    physical: 72,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(224231),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(89),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'carvajal',
    name: 'Dani Carvajal',
    shortName: 'Carvajal',
    position: 'RB',
    rating: 87,
    pace: 83,
    shooting: 61,
    passing: 79,
    dribbling: 79,
    defending: 88,
    physical: 78,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(184319),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(87),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'alaba',
    name: 'David Alaba',
    shortName: 'D. Alaba',
    position: 'CB',
    rating: 87,
    pace: 77,
    shooting: 61,
    passing: 76,
    dribbling: 75,
    defending: 87,
    physical: 79,
    nationality: 'AT',
    nationalityFull: 'Austria',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(192119),
    flagUrl: flag('at'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(87),
    editions: LIGA_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'militao',
    name: 'Éder Militão',
    shortName: 'E. Militão',
    position: 'CB',
    rating: 87,
    pace: 85,
    shooting: 44,
    passing: 67,
    dribbling: 68,
    defending: 88,
    physical: 86,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(237025),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(87),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'griezmann',
    name: 'Antoine Griezmann',
    shortName: 'Griezmann',
    position: 'CAM',
    rating: 88,
    pace: 79,
    shooting: 87,
    passing: 84,
    dribbling: 87,
    defending: 51,
    physical: 74,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Atlético Madrid',
    league: 'La Liga',
    imageUrl: sfImg(194765),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('530'),
    baseValue: getBaseValue(88),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'oblak',
    name: 'Jan Oblak',
    shortName: 'J. Oblak',
    position: 'GK',
    rating: 89,
    pace: 55,
    shooting: 14,
    passing: 62,
    dribbling: 22,
    defending: 18,
    physical: 79,
    nationality: 'SI',
    nationalityFull: 'Slovenia',
    club: 'Atlético Madrid',
    league: 'La Liga',
    imageUrl: sfImg(200389),
    flagUrl: flag('si'),
    clubBadgeUrl: badge('530'),
    baseValue: getBaseValue(89),
    editions: LIGA_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'de-gea',
    name: 'David De Gea',
    shortName: 'De Gea',
    position: 'GK',
    rating: 87,
    pace: 42,
    shooting: 20,
    passing: 56,
    dribbling: 18,
    defending: 17,
    physical: 72,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Fiorentina',
    league: 'Serie A',
    imageUrl: sfImg(177003),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('502'),
    baseValue: getBaseValue(87),
    editions: ['custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'bruno',
    name: 'Bruno Fernandes',
    shortName: 'B. Fernandes',
    position: 'CAM',
    rating: 88,
    pace: 75,
    shooting: 85,
    passing: 90,
    dribbling: 86,
    defending: 60,
    physical: 73,
    nationality: 'PT',
    nationalityFull: 'Portugal',
    club: 'Manchester United',
    league: 'Premier League',
    imageUrl: sfImg(212319),
    flagUrl: flag('pt'),
    clubBadgeUrl: badge('33'),
    baseValue: getBaseValue(88),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'foden',
    name: 'Phil Foden',
    shortName: 'P. Foden',
    position: 'LW',
    rating: 88,
    pace: 84,
    shooting: 86,
    passing: 86,
    dribbling: 91,
    defending: 57,
    physical: 68,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Manchester City',
    league: 'Premier League',
    imageUrl: sfImg(237663),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('50'),
    baseValue: getBaseValue(88),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'firmino',
    name: 'Roberto Firmino',
    shortName: 'R. Firmino',
    position: 'ST',
    rating: 86,
    pace: 82,
    shooting: 85,
    passing: 82,
    dribbling: 85,
    defending: 48,
    physical: 73,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Al Ahli',
    league: 'Saudi Pro League',
    imageUrl: sfImg(200145),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('2938'),
    baseValue: getBaseValue(86),
    editions: ['world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'coman',
    name: 'Kingsley Coman',
    shortName: 'K. Coman',
    position: 'LW',
    rating: 86,
    pace: 94,
    shooting: 79,
    passing: 78,
    dribbling: 89,
    defending: 38,
    physical: 73,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Bayern Munich',
    league: 'Bundesliga',
    imageUrl: sfImg(211088),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('157'),
    baseValue: getBaseValue(86),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'kane',
    name: 'Harry Kane',
    shortName: 'H. Kane',
    position: 'ST',
    rating: 89,
    pace: 72,
    shooting: 93,
    passing: 82,
    dribbling: 80,
    defending: 47,
    physical: 83,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Bayern Munich',
    league: 'Bundesliga',
    imageUrl: sfImg(202126),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('157'),
    baseValue: getBaseValue(89),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'musiala',
    name: 'Jamal Musiala',
    shortName: 'J. Musiala',
    position: 'CAM',
    rating: 89,
    pace: 85,
    shooting: 83,
    passing: 83,
    dribbling: 92,
    defending: 54,
    physical: 66,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Bayern Munich',
    league: 'Bundesliga',
    imageUrl: sfImg(278250),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('157'),
    baseValue: getBaseValue(89),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'goretzka',
    name: 'Leon Goretzka',
    shortName: 'L. Goretzka',
    position: 'CM',
    rating: 86,
    pace: 79,
    shooting: 80,
    passing: 83,
    dribbling: 80,
    defending: 80,
    physical: 86,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Bayern Munich',
    league: 'Bundesliga',
    imageUrl: sfImg(213386),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('157'),
    baseValue: getBaseValue(86),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'neuer',
    name: 'Manuel Neuer',
    shortName: 'M. Neuer',
    position: 'GK',
    rating: 87,
    pace: 58,
    shooting: 22,
    passing: 72,
    dribbling: 30,
    defending: 26,
    physical: 82,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Bayern Munich',
    league: 'Bundesliga',
    imageUrl: sfImg(167495),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('157'),
    baseValue: getBaseValue(87),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'pulisic',
    name: 'Christian Pulisic',
    shortName: 'C. Pulisic',
    position: 'RW',
    rating: 85,
    pace: 90,
    shooting: 81,
    passing: 79,
    dribbling: 88,
    defending: 49,
    physical: 67,
    nationality: 'US',
    nationalityFull: 'United States',
    club: 'AC Milan',
    league: 'Serie A',
    imageUrl: sfImg(221648),
    flagUrl: flag('us'),
    clubBadgeUrl: badge('489'),
    baseValue: getBaseValue(85),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'theo-walcott',
    name: 'Theo Walcott',
    shortName: 'T. Walcott',
    position: 'RW',
    rating: 85,
    pace: 97,
    shooting: 80,
    passing: 73,
    dribbling: 82,
    defending: 35,
    physical: 67,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Retired',
    league: 'Premier League',
    imageUrl: sfImg(155394),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(85),
    editions: ['custom'],
    isLegend: false,
    era: 'Legend',
  },
  {
    id: 'benzema',
    name: 'Karim Benzema',
    shortName: 'K. Benzema',
    position: 'ST',
    rating: 89,
    pace: 76,
    shooting: 89,
    passing: 82,
    dribbling: 87,
    defending: 39,
    physical: 80,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Al Ittihad',
    league: 'Saudi Pro League',
    imageUrl: sfImg(165153),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('2929'),
    baseValue: getBaseValue(89),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'modric',
    name: 'Luka Modrić',
    shortName: 'Modrić',
    position: 'CM',
    rating: 88,
    pace: 73,
    shooting: 76,
    passing: 91,
    dribbling: 91,
    defending: 72,
    physical: 65,
    nationality: 'HR',
    nationalityFull: 'Croatia',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(177003),
    flagUrl: flag('hr'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(88),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'neymar',
    name: 'Neymar Jr.',
    shortName: 'Neymar Jr.',
    position: 'LW',
    rating: 89,
    pace: 87,
    shooting: 87,
    passing: 87,
    dribbling: 96,
    defending: 32,
    physical: 63,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Al Hilal',
    league: 'Saudi Pro League',
    imageUrl: sfImg(190871),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('2933'),
    baseValue: getBaseValue(89),
    editions: ['world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'thiago-silva',
    name: 'Thiago Silva',
    shortName: 'T. Silva',
    position: 'CB',
    rating: 87,
    pace: 73,
    shooting: 44,
    passing: 75,
    dribbling: 68,
    defending: 91,
    physical: 84,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Fluminense',
    league: 'Brasileirão',
    imageUrl: sfImg(183026),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('121'),
    baseValue: getBaseValue(87),
    editions: ['world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'suarez',
    name: 'Luis Suárez',
    shortName: 'L. Suárez',
    position: 'ST',
    rating: 88,
    pace: 77,
    shooting: 91,
    passing: 77,
    dribbling: 85,
    defending: 38,
    physical: 78,
    nationality: 'UY',
    nationalityFull: 'Uruguay',
    club: 'Inter Miami CF',
    league: 'MLS',
    imageUrl: sfImg(176580),
    flagUrl: flag('uy'),
    clubBadgeUrl: badge('10714'),
    baseValue: getBaseValue(88),
    editions: ['world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'roberto-carlos',
    name: 'Roberto Carlos',
    shortName: 'R. Carlos',
    position: 'LB',
    rating: 87,
    pace: 88,
    shooting: 80,
    passing: 77,
    dribbling: 82,
    defending: 86,
    physical: 82,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(8),
    flagUrl: flag('br'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'cafu',
    name: 'Cafu',
    shortName: 'Cafu',
    position: 'RB',
    rating: 87,
    pace: 87,
    shooting: 71,
    passing: 76,
    dribbling: 82,
    defending: 84,
    physical: 83,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(9),
    flagUrl: flag('br'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'seedorf',
    name: 'Clarence Seedorf',
    shortName: 'Seedorf',
    position: 'CM',
    rating: 87,
    pace: 80,
    shooting: 83,
    passing: 84,
    dribbling: 85,
    defending: 70,
    physical: 78,
    nationality: 'NL',
    nationalityFull: 'Netherlands',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(10),
    flagUrl: flag('nl'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'shevchenko',
    name: 'Andriy Shevchenko',
    shortName: 'Shevchenko',
    position: 'ST',
    rating: 88,
    pace: 88,
    shooting: 92,
    passing: 74,
    dribbling: 84,
    defending: 35,
    physical: 80,
    nationality: 'UA',
    nationalityFull: 'Ukraine',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(11),
    flagUrl: flag('ua'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(88),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'drogba',
    name: 'Didier Drogba',
    shortName: 'D. Drogba',
    position: 'ST',
    rating: 88,
    pace: 82,
    shooting: 90,
    passing: 71,
    dribbling: 79,
    defending: 35,
    physical: 92,
    nationality: 'CI',
    nationalityFull: "Côte d'Ivoire",
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(13),
    flagUrl: flag('ci'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(88),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'gerrard',
    name: 'Steven Gerrard',
    shortName: 'S. Gerrard',
    position: 'CM',
    rating: 88,
    pace: 79,
    shooting: 86,
    passing: 87,
    dribbling: 83,
    defending: 79,
    physical: 87,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(14),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(88),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'lampard',
    name: 'Frank Lampard',
    shortName: 'F. Lampard',
    position: 'CM',
    rating: 87,
    pace: 74,
    shooting: 87,
    passing: 83,
    dribbling: 79,
    defending: 76,
    physical: 79,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(15),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'vieira',
    name: 'Patrick Vieira',
    shortName: 'P. Vieira',
    position: 'CDM',
    rating: 87,
    pace: 81,
    shooting: 76,
    passing: 82,
    dribbling: 78,
    defending: 86,
    physical: 90,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(16),
    flagUrl: flag('fr'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'kaka',
    name: 'Kaká',
    shortName: 'Kaká',
    position: 'CAM',
    rating: 88,
    pace: 86,
    shooting: 85,
    passing: 91,
    dribbling: 91,
    defending: 46,
    physical: 73,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(17),
    flagUrl: flag('br'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(88),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'rooney',
    name: 'Wayne Rooney',
    shortName: 'W. Rooney',
    position: 'ST',
    rating: 87,
    pace: 78,
    shooting: 88,
    passing: 77,
    dribbling: 83,
    defending: 43,
    physical: 83,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(18),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'ibrahimovic',
    name: 'Zlatan Ibrahimović',
    shortName: 'Z. Ibrahimović',
    position: 'ST',
    rating: 88,
    pace: 79,
    shooting: 91,
    passing: 78,
    dribbling: 87,
    defending: 37,
    physical: 86,
    nationality: 'SE',
    nationalityFull: 'Sweden',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(19),
    flagUrl: flag('se'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(88),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'ribery',
    name: 'Franck Ribéry',
    shortName: 'F. Ribéry',
    position: 'LW',
    rating: 87,
    pace: 89,
    shooting: 79,
    passing: 84,
    dribbling: 94,
    defending: 42,
    physical: 73,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(20),
    flagUrl: flag('fr'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'robben',
    name: 'Arjen Robben',
    shortName: 'A. Robben',
    position: 'RW',
    rating: 87,
    pace: 91,
    shooting: 87,
    passing: 78,
    dribbling: 92,
    defending: 33,
    physical: 70,
    nationality: 'NL',
    nationalityFull: 'Netherlands',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(21),
    flagUrl: flag('nl'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'dybala',
    name: 'Paulo Dybala',
    shortName: 'P. Dybala',
    position: 'CAM',
    rating: 86,
    pace: 83,
    shooting: 85,
    passing: 82,
    dribbling: 90,
    defending: 37,
    physical: 66,
    nationality: 'AR',
    nationalityFull: 'Argentina',
    club: 'AS Roma',
    league: 'Serie A',
    imageUrl: sfImg(210049),
    flagUrl: flag('ar'),
    clubBadgeUrl: badge('497'),
    baseValue: getBaseValue(86),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'mendy',
    name: 'Benjamin Mendy',
    shortName: 'B. Mendy',
    position: 'LB',
    rating: 85,
    pace: 87,
    shooting: 59,
    passing: 73,
    dribbling: 73,
    defending: 84,
    physical: 79,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Retired',
    league: 'custom',
    imageUrl: sfImg(218667),
    flagUrl: flag('fr'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(85),
    editions: ['custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'varane',
    name: 'Raphaël Varane',
    shortName: 'R. Varane',
    position: 'CB',
    rating: 87,
    pace: 85,
    shooting: 47,
    passing: 71,
    dribbling: 70,
    defending: 90,
    physical: 86,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Como',
    league: 'Serie A',
    imageUrl: sfImg(198681),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('484'),
    baseValue: getBaseValue(87),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'danilo',
    name: 'Danilo',
    shortName: 'Danilo',
    position: 'RB',
    rating: 85,
    pace: 78,
    shooting: 60,
    passing: 76,
    dribbling: 70,
    defending: 84,
    physical: 82,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Flamengo',
    league: 'Brasileirão',
    imageUrl: sfImg(192505),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('141'),
    baseValue: getBaseValue(85),
    editions: ['world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'dias-ruben',
    name: 'João Cancelo',
    shortName: 'J. Cancelo',
    position: 'RB',
    rating: 87,
    pace: 82,
    shooting: 67,
    passing: 81,
    dribbling: 82,
    defending: 83,
    physical: 75,
    nationality: 'PT',
    nationalityFull: 'Portugal',
    club: 'FC Barcelona',
    league: 'La Liga',
    imageUrl: sfImg(222665),
    flagUrl: flag('pt'),
    clubBadgeUrl: badge('529'),
    baseValue: getBaseValue(87),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'dest',
    name: 'Sergiño Dest',
    shortName: 'S. Dest',
    position: 'RB',
    rating: 85,
    pace: 88,
    shooting: 72,
    passing: 74,
    dribbling: 83,
    defending: 77,
    physical: 68,
    nationality: 'US',
    nationalityFull: 'United States',
    club: 'PSV Eindhoven',
    league: 'Eredivisie',
    imageUrl: sfImg(250066),
    flagUrl: flag('us'),
    clubBadgeUrl: badge('672'),
    baseValue: getBaseValue(85),
    editions: ['world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'depay',
    name: 'Memphis Depay',
    shortName: 'M. Depay',
    position: 'ST',
    rating: 86,
    pace: 88,
    shooting: 85,
    passing: 79,
    dribbling: 88,
    defending: 37,
    physical: 73,
    nationality: 'NL',
    nationalityFull: 'Netherlands',
    club: 'Corinthians',
    league: 'Brasileirão',
    imageUrl: sfImg(208170),
    flagUrl: flag('nl'),
    clubBadgeUrl: badge('131'),
    baseValue: getBaseValue(86),
    editions: ['world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'lukaku',
    name: 'Romelu Lukaku',
    shortName: 'R. Lukaku',
    position: 'ST',
    rating: 86,
    pace: 83,
    shooting: 86,
    passing: 64,
    dribbling: 79,
    defending: 42,
    physical: 91,
    nationality: 'BE',
    nationalityFull: 'Belgium',
    club: 'AS Roma',
    league: 'Serie A',
    imageUrl: sfImg(192505),
    flagUrl: flag('be'),
    clubBadgeUrl: badge('497'),
    baseValue: getBaseValue(86),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'hazard',
    name: 'Eden Hazard',
    shortName: 'E. Hazard',
    position: 'LW',
    rating: 88,
    pace: 89,
    shooting: 84,
    passing: 84,
    dribbling: 94,
    defending: 34,
    physical: 72,
    nationality: 'BE',
    nationalityFull: 'Belgium',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(183277),
    flagUrl: flag('be'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(88),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'sterling',
    name: 'Raheem Sterling',
    shortName: 'R. Sterling',
    position: 'LW',
    rating: 86,
    pace: 91,
    shooting: 84,
    passing: 80,
    dribbling: 88,
    defending: 44,
    physical: 67,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Arsenal',
    league: 'Premier League',
    imageUrl: sfImg(200025),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('42'),
    baseValue: getBaseValue(86),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'walker',
    name: 'Kyle Walker',
    shortName: 'K. Walker',
    position: 'RB',
    rating: 86,
    pace: 92,
    shooting: 60,
    passing: 73,
    dribbling: 73,
    defending: 85,
    physical: 81,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'AC Milan',
    league: 'Serie A',
    imageUrl: sfImg(193080),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('489'),
    baseValue: getBaseValue(86),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'stones',
    name: 'John Stones',
    shortName: 'J. Stones',
    position: 'CB',
    rating: 86,
    pace: 72,
    shooting: 45,
    passing: 75,
    dribbling: 68,
    defending: 87,
    physical: 81,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Manchester City',
    league: 'Premier League',
    imageUrl: sfImg(205687),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('50'),
    baseValue: getBaseValue(86),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'martinez-lautaro',
    name: 'Lautaro Martínez',
    shortName: 'L. Martínez',
    position: 'ST',
    rating: 88,
    pace: 82,
    shooting: 89,
    passing: 74,
    dribbling: 86,
    defending: 43,
    physical: 78,
    nationality: 'AR',
    nationalityFull: 'Argentina',
    club: 'Inter Milan',
    league: 'Serie A',
    imageUrl: sfImg(241084),
    flagUrl: flag('ar'),
    clubBadgeUrl: badge('505'),
    baseValue: getBaseValue(88),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'calhanoglu',
    name: 'Hakan Çalhanoğlu',
    shortName: 'H. Çalhanoğlu',
    position: 'CDM',
    rating: 86,
    pace: 64,
    shooting: 80,
    passing: 86,
    dribbling: 82,
    defending: 80,
    physical: 73,
    nationality: 'TR',
    nationalityFull: 'Turkey',
    club: 'Inter Milan',
    league: 'Serie A',
    imageUrl: sfImg(212014),
    flagUrl: flag('tr'),
    clubBadgeUrl: badge('505'),
    baseValue: getBaseValue(86),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'barella',
    name: 'Nicolò Barella',
    shortName: 'N. Barella',
    position: 'CM',
    rating: 87,
    pace: 78,
    shooting: 77,
    passing: 86,
    dribbling: 84,
    defending: 81,
    physical: 80,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Inter Milan',
    league: 'Serie A',
    imageUrl: sfImg(238690),
    flagUrl: flag('it'),
    clubBadgeUrl: badge('505'),
    baseValue: getBaseValue(87),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'dimarco',
    name: 'Federico Dimarco',
    shortName: 'F. Dimarco',
    position: 'LB',
    rating: 85,
    pace: 79,
    shooting: 74,
    passing: 81,
    dribbling: 74,
    defending: 84,
    physical: 76,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Inter Milan',
    league: 'Serie A',
    imageUrl: sfImg(246419),
    flagUrl: flag('it'),
    clubBadgeUrl: badge('505'),
    baseValue: getBaseValue(85),
    editions: ['champions-league', 'custom'],
    isLegend: false,
    era: 'Modern',
  },

  // ========================================
  // GOLD (Rating 80–84) — 80 players
  // ========================================
  {
    id: 'trippier',
    name: 'Kieran Trippier',
    shortName: 'K. Trippier',
    position: 'RB',
    rating: 84,
    pace: 77,
    shooting: 68,
    passing: 83,
    dribbling: 67,
    defending: 83,
    physical: 72,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Newcastle United',
    league: 'Premier League',
    imageUrl: sfImg(198517),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('67'),
    baseValue: getBaseValue(84),
    editions: PL_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'chilwell',
    name: 'Ben Chilwell',
    shortName: 'B. Chilwell',
    position: 'LB',
    rating: 82,
    pace: 80,
    shooting: 63,
    passing: 74,
    dribbling: 72,
    defending: 80,
    physical: 73,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Chelsea',
    league: 'Premier League',
    imageUrl: sfImg(230686),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('49'),
    baseValue: getBaseValue(82),
    editions: PL_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'laporte',
    name: 'Aymeric Laporte',
    shortName: 'A. Laporte',
    position: 'CB',
    rating: 84,
    pace: 76,
    shooting: 44,
    passing: 77,
    dribbling: 64,
    defending: 87,
    physical: 81,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Al Nassr',
    league: 'Saudi Pro League',
    imageUrl: sfImg(210031),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('2932'),
    baseValue: getBaseValue(84),
    editions: ['world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'gundogan',
    name: 'İlkay Gündoğan',
    shortName: 'İ. Gündoğan',
    position: 'CM',
    rating: 84,
    pace: 67,
    shooting: 80,
    passing: 86,
    dribbling: 82,
    defending: 73,
    physical: 71,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'FC Barcelona',
    league: 'La Liga',
    imageUrl: sfImg(186153),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('529'),
    baseValue: getBaseValue(84),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'mount',
    name: 'Mason Mount',
    shortName: 'M. Mount',
    position: 'CAM',
    rating: 82,
    pace: 79,
    shooting: 79,
    passing: 82,
    dribbling: 83,
    defending: 67,
    physical: 68,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Manchester United',
    league: 'Premier League',
    imageUrl: sfImg(230781),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('33'),
    baseValue: getBaseValue(82),
    editions: PL_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'james-reece',
    name: 'Reece James',
    shortName: 'R. James',
    position: 'RB',
    rating: 84,
    pace: 79,
    shooting: 72,
    passing: 77,
    dribbling: 76,
    defending: 84,
    physical: 82,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Chelsea',
    league: 'Premier League',
    imageUrl: sfImg(244652),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('49'),
    baseValue: getBaseValue(84),
    editions: [...PL_EDITIONS, 'champions-league'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'kimmich',
    name: 'Joshua Kimmich',
    shortName: 'J. Kimmich',
    position: 'CDM',
    rating: 88,
    pace: 71,
    shooting: 72,
    passing: 88,
    dribbling: 80,
    defending: 86,
    physical: 73,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Bayern Munich',
    league: 'Bundesliga',
    imageUrl: sfImg(214032),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('157'),
    baseValue: getBaseValue(88),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'thuram',
    name: 'Marcus Thuram',
    shortName: 'M. Thuram',
    position: 'ST',
    rating: 84,
    pace: 90,
    shooting: 82,
    passing: 72,
    dribbling: 83,
    defending: 42,
    physical: 84,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Inter Milan',
    league: 'Serie A',
    imageUrl: sfImg(241107),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('505'),
    baseValue: getBaseValue(84),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'zaniolo',
    name: 'Nicolò Zaniolo',
    shortName: 'N. Zaniolo',
    position: 'CAM',
    rating: 82,
    pace: 82,
    shooting: 78,
    passing: 73,
    dribbling: 82,
    defending: 45,
    physical: 77,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Fiorentina',
    league: 'Serie A',
    imageUrl: sfImg(240014),
    flagUrl: flag('it'),
    clubBadgeUrl: badge('502'),
    baseValue: getBaseValue(82),
    editions: ['custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'chukwueze',
    name: 'Samuel Chukwueze',
    shortName: 'S. Chukwueze',
    position: 'RW',
    rating: 81,
    pace: 94,
    shooting: 76,
    passing: 68,
    dribbling: 83,
    defending: 38,
    physical: 68,
    nationality: 'NG',
    nationalityFull: 'Nigeria',
    club: 'AC Milan',
    league: 'Serie A',
    imageUrl: sfImg(240485),
    flagUrl: flag('ng'),
    clubBadgeUrl: badge('489'),
    baseValue: getBaseValue(81),
    editions: ['champions-league', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'havertz',
    name: 'Kai Havertz',
    shortName: 'K. Havertz',
    position: 'ST',
    rating: 84,
    pace: 80,
    shooting: 82,
    passing: 80,
    dribbling: 82,
    defending: 56,
    physical: 78,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Arsenal',
    league: 'Premier League',
    imageUrl: sfImg(223205),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('42'),
    baseValue: getBaseValue(84),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'odegaard',
    name: 'Martin Ødegaard',
    shortName: 'M. Ødegaard',
    position: 'CAM',
    rating: 88,
    pace: 77,
    shooting: 83,
    passing: 89,
    dribbling: 88,
    defending: 62,
    physical: 65,
    nationality: 'NO',
    nationalityFull: 'Norway',
    club: 'Arsenal',
    league: 'Premier League',
    imageUrl: sfImg(222028),
    flagUrl: flag('no'),
    clubBadgeUrl: badge('42'),
    baseValue: getBaseValue(88),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'white-ben',
    name: 'Ben White',
    shortName: 'B. White',
    position: 'RB',
    rating: 83,
    pace: 75,
    shooting: 48,
    passing: 72,
    dribbling: 66,
    defending: 84,
    physical: 77,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Arsenal',
    league: 'Premier League',
    imageUrl: sfImg(239017),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('42'),
    baseValue: getBaseValue(83),
    editions: [...PL_EDITIONS, 'champions-league'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'gabriel',
    name: 'Gabriel Magalhães',
    shortName: 'Gabriel',
    position: 'CB',
    rating: 84,
    pace: 74,
    shooting: 47,
    passing: 67,
    dribbling: 57,
    defending: 86,
    physical: 87,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Arsenal',
    league: 'Premier League',
    imageUrl: sfImg(242564),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('42'),
    baseValue: getBaseValue(84),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'tomiyasu',
    name: 'Takehiro Tomiyasu',
    shortName: 'T. Tomiyasu',
    position: 'RB',
    rating: 81,
    pace: 75,
    shooting: 42,
    passing: 70,
    dribbling: 63,
    defending: 82,
    physical: 77,
    nationality: 'JP',
    nationalityFull: 'Japan',
    club: 'Arsenal',
    league: 'Premier League',
    imageUrl: sfImg(237677),
    flagUrl: flag('jp'),
    clubBadgeUrl: badge('42'),
    baseValue: getBaseValue(81),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'saliba',
    name: 'William Saliba',
    shortName: 'W. Saliba',
    position: 'CB',
    rating: 86,
    pace: 82,
    shooting: 44,
    passing: 71,
    dribbling: 65,
    defending: 87,
    physical: 84,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Arsenal',
    league: 'Premier League',
    imageUrl: sfImg(246183),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('42'),
    baseValue: getBaseValue(86),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'xhaka',
    name: 'Granit Xhaka',
    shortName: 'G. Xhaka',
    position: 'CDM',
    rating: 83,
    pace: 64,
    shooting: 72,
    passing: 82,
    dribbling: 72,
    defending: 79,
    physical: 80,
    nationality: 'CH',
    nationalityFull: 'Switzerland',
    club: 'Bayer Leverkusen',
    league: 'Bundesliga',
    imageUrl: sfImg(194638),
    flagUrl: flag('ch'),
    clubBadgeUrl: badge('168'),
    baseValue: getBaseValue(83),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'wirtz',
    name: 'Florian Wirtz',
    shortName: 'F. Wirtz',
    position: 'CAM',
    rating: 88,
    pace: 79,
    shooting: 83,
    passing: 87,
    dribbling: 90,
    defending: 52,
    physical: 67,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Bayer Leverkusen',
    league: 'Bundesliga',
    imageUrl: sfImg(267789),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('168'),
    baseValue: getBaseValue(88),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'boniface',
    name: 'Victor Boniface',
    shortName: 'V. Boniface',
    position: 'ST',
    rating: 83,
    pace: 90,
    shooting: 81,
    passing: 69,
    dribbling: 82,
    defending: 38,
    physical: 83,
    nationality: 'NG',
    nationalityFull: 'Nigeria',
    club: 'Bayer Leverkusen',
    league: 'Bundesliga',
    imageUrl: sfImg(278258),
    flagUrl: flag('ng'),
    clubBadgeUrl: badge('168'),
    baseValue: getBaseValue(83),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'grimaldo',
    name: 'Alejandro Grimaldo',
    shortName: 'A. Grimaldo',
    position: 'LB',
    rating: 84,
    pace: 82,
    shooting: 72,
    passing: 80,
    dribbling: 78,
    defending: 82,
    physical: 72,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Bayer Leverkusen',
    league: 'Bundesliga',
    imageUrl: sfImg(212005),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('168'),
    baseValue: getBaseValue(84),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'tah',
    name: 'Jonathan Tah',
    shortName: 'J. Tah',
    position: 'CB',
    rating: 83,
    pace: 79,
    shooting: 39,
    passing: 68,
    dribbling: 58,
    defending: 85,
    physical: 84,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Bayern Munich',
    league: 'Bundesliga',
    imageUrl: sfImg(212726),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('157'),
    baseValue: getBaseValue(83),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'gnabry',
    name: 'Serge Gnabry',
    shortName: 'S. Gnabry',
    position: 'RW',
    rating: 84,
    pace: 91,
    shooting: 83,
    passing: 76,
    dribbling: 86,
    defending: 44,
    physical: 71,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Bayern Munich',
    league: 'Bundesliga',
    imageUrl: sfImg(213997),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('157'),
    baseValue: getBaseValue(84),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'sane',
    name: 'Leroy Sané',
    shortName: 'L. Sané',
    position: 'RW',
    rating: 85,
    pace: 95,
    shooting: 81,
    passing: 77,
    dribbling: 88,
    defending: 40,
    physical: 72,
    nationality: 'DE',
    nationalityFull: 'Germany',
    club: 'Bayern Munich',
    league: 'Bundesliga',
    imageUrl: sfImg(213997),
    flagUrl: flag('de'),
    clubBadgeUrl: badge('157'),
    baseValue: getBaseValue(85),
    editions: [...BUND_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'nkunku',
    name: 'Christopher Nkunku',
    shortName: 'C. Nkunku',
    position: 'CAM',
    rating: 85,
    pace: 87,
    shooting: 84,
    passing: 80,
    dribbling: 87,
    defending: 50,
    physical: 70,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Chelsea',
    league: 'Premier League',
    imageUrl: sfImg(227651),
    flagUrl: flag('fr'),
    clubBadgeUrl: badge('49'),
    baseValue: getBaseValue(85),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'cucurella',
    name: 'Marc Cucurella',
    shortName: 'M. Cucurella',
    position: 'LB',
    rating: 82,
    pace: 80,
    shooting: 58,
    passing: 73,
    dribbling: 76,
    defending: 81,
    physical: 72,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Chelsea',
    league: 'Premier League',
    imageUrl: sfImg(241045),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('49'),
    baseValue: getBaseValue(82),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'palmer',
    name: 'Cole Palmer',
    shortName: 'C. Palmer',
    position: 'CAM',
    rating: 87,
    pace: 77,
    shooting: 86,
    passing: 85,
    dribbling: 88,
    defending: 50,
    physical: 66,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Chelsea',
    league: 'Premier League',
    imageUrl: sfImg(273498),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('49'),
    baseValue: getBaseValue(87),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'fernandez-enzo',
    name: 'Enzo Fernández',
    shortName: 'E. Fernández',
    position: 'CM',
    rating: 84,
    pace: 72,
    shooting: 76,
    passing: 84,
    dribbling: 82,
    defending: 77,
    physical: 74,
    nationality: 'AR',
    nationalityFull: 'Argentina',
    club: 'Chelsea',
    league: 'Premier League',
    imageUrl: sfImg(265360),
    flagUrl: flag('ar'),
    clubBadgeUrl: badge('49'),
    baseValue: getBaseValue(84),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'caicedo',
    name: 'Moisés Caicedo',
    shortName: 'M. Caicedo',
    position: 'CDM',
    rating: 84,
    pace: 76,
    shooting: 62,
    passing: 79,
    dribbling: 76,
    defending: 83,
    physical: 82,
    nationality: 'EC',
    nationalityFull: 'Ecuador',
    club: 'Chelsea',
    league: 'Premier League',
    imageUrl: sfImg(267700),
    flagUrl: flag('ec'),
    clubBadgeUrl: badge('49'),
    baseValue: getBaseValue(84),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'sancho',
    name: 'Jadon Sancho',
    shortName: 'J. Sancho',
    position: 'RW',
    rating: 82,
    pace: 87,
    shooting: 77,
    passing: 78,
    dribbling: 87,
    defending: 40,
    physical: 65,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Chelsea',
    league: 'Premier League',
    imageUrl: sfImg(231677),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('49'),
    baseValue: getBaseValue(82),
    editions: PL_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'Jimenez',
    name: 'Raúl Jiménez',
    shortName: 'R. Jiménez',
    position: 'ST',
    rating: 80,
    pace: 77,
    shooting: 81,
    passing: 68,
    dribbling: 76,
    defending: 32,
    physical: 78,
    nationality: 'MX',
    nationalityFull: 'Mexico',
    club: 'Fulham',
    league: 'Premier League',
    imageUrl: sfImg(206568),
    flagUrl: flag('mx'),
    clubBadgeUrl: badge('57'),
    baseValue: getBaseValue(80),
    editions: PL_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'willian',
    name: 'Willian',
    shortName: 'Willian',
    position: 'RW',
    rating: 80,
    pace: 83,
    shooting: 74,
    passing: 78,
    dribbling: 82,
    defending: 38,
    physical: 70,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Fluminense',
    league: 'Brasileirão',
    imageUrl: sfImg(184523),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('121'),
    baseValue: getBaseValue(80),
    editions: ['custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'dani-alves',
    name: 'Dani Alves',
    shortName: 'D. Alves',
    position: 'RB',
    rating: 82,
    pace: 81,
    shooting: 68,
    passing: 79,
    dribbling: 82,
    defending: 80,
    physical: 73,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(35725),
    flagUrl: flag('br'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(82),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'riquelme',
    name: 'Juan Román Riquelme',
    shortName: 'J.R. Riquelme',
    position: 'CAM',
    rating: 87,
    pace: 60,
    shooting: 80,
    passing: 95,
    dribbling: 88,
    defending: 32,
    physical: 63,
    nationality: 'AR',
    nationalityFull: 'Argentina',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(22),
    flagUrl: flag('ar'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'totti',
    name: 'Francesco Totti',
    shortName: 'F. Totti',
    position: 'CAM',
    rating: 88,
    pace: 79,
    shooting: 86,
    passing: 90,
    dribbling: 92,
    defending: 40,
    physical: 74,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(23),
    flagUrl: flag('it'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(88),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'del-piero',
    name: 'Alessandro Del Piero',
    shortName: 'A. Del Piero',
    position: 'CAM',
    rating: 88,
    pace: 77,
    shooting: 88,
    passing: 88,
    dribbling: 87,
    defending: 37,
    physical: 75,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(24),
    flagUrl: flag('it'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(88),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'nedved',
    name: 'Pavel Nedvěd',
    shortName: 'P. Nedvěd',
    position: 'LW',
    rating: 87,
    pace: 83,
    shooting: 86,
    passing: 85,
    dribbling: 86,
    defending: 56,
    physical: 79,
    nationality: 'CZ',
    nationalityFull: 'Czech Republic',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(25),
    flagUrl: flag('cz'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'figo',
    name: 'Luís Figo',
    shortName: 'L. Figo',
    position: 'RW',
    rating: 88,
    pace: 85,
    shooting: 82,
    passing: 88,
    dribbling: 93,
    defending: 37,
    physical: 76,
    nationality: 'PT',
    nationalityFull: 'Portugal',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(26),
    flagUrl: flag('pt'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(88),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'giggs',
    name: 'Ryan Giggs',
    shortName: 'R. Giggs',
    position: 'LW',
    rating: 87,
    pace: 90,
    shooting: 78,
    passing: 81,
    dribbling: 92,
    defending: 40,
    physical: 71,
    nationality: 'GB-WLS',
    nationalityFull: 'Wales',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(27),
    flagUrl: flag('gb-wls'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'scholes',
    name: 'Paul Scholes',
    shortName: 'P. Scholes',
    position: 'CM',
    rating: 87,
    pace: 66,
    shooting: 85,
    passing: 88,
    dribbling: 80,
    defending: 77,
    physical: 77,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(28),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Legend',
  },
  {
    id: 'ferdinand',
    name: 'Rio Ferdinand',
    shortName: 'R. Ferdinand',
    position: 'CB',
    rating: 87,
    pace: 80,
    shooting: 43,
    passing: 66,
    dribbling: 60,
    defending: 91,
    physical: 84,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(29),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'cantona',
    name: 'Eric Cantona',
    shortName: 'E. Cantona',
    position: 'ST',
    rating: 87,
    pace: 77,
    shooting: 87,
    passing: 82,
    dribbling: 88,
    defending: 35,
    physical: 85,
    nationality: 'FR',
    nationalityFull: 'France',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(31),
    flagUrl: flag('fr'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(87),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },
  {
    id: 'butragueno',
    name: 'Emilio Butragueño',
    shortName: 'E. Butragueño',
    position: 'ST',
    rating: 82,
    pace: 83,
    shooting: 86,
    passing: 73,
    dribbling: 82,
    defending: 28,
    physical: 68,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Retired',
    league: 'Icon',
    imageUrl: sfImg(32),
    flagUrl: flag('es'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(82),
    editions: LEGEND_EDITIONS,
    isLegend: true,
    era: 'Icon',
  },

  // ========================================
  // SILVER / BRONZE (Rating < 80) — 20 players
  // ========================================
  {
    id: 'garnacho',
    name: 'Alejandro Garnacho',
    shortName: 'A. Garnacho',
    position: 'LW',
    rating: 79,
    pace: 87,
    shooting: 74,
    passing: 72,
    dribbling: 82,
    defending: 36,
    physical: 64,
    nationality: 'AR',
    nationalityFull: 'Argentina',
    club: 'Manchester United',
    league: 'Premier League',
    imageUrl: sfImg(267637),
    flagUrl: flag('ar'),
    clubBadgeUrl: badge('33'),
    baseValue: getBaseValue(79),
    editions: PL_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'mainoo',
    name: 'Kobbie Mainoo',
    shortName: 'K. Mainoo',
    position: 'CM',
    rating: 77,
    pace: 73,
    shooting: 68,
    passing: 76,
    dribbling: 78,
    defending: 72,
    physical: 72,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Manchester United',
    league: 'Premier League',
    imageUrl: sfImg(277508),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('33'),
    baseValue: getBaseValue(77),
    editions: PL_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'guiu',
    name: 'Marc Guiu',
    shortName: 'M. Guiu',
    position: 'ST',
    rating: 73,
    pace: 76,
    shooting: 72,
    passing: 63,
    dribbling: 70,
    defending: 28,
    physical: 70,
    nationality: 'ES',
    nationalityFull: 'Spain',
    club: 'Chelsea',
    league: 'Premier League',
    imageUrl: sfImg(278562),
    flagUrl: flag('es'),
    clubBadgeUrl: badge('49'),
    baseValue: getBaseValue(73),
    editions: PL_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'palmer-carlton',
    name: 'Carlton Palmer',
    shortName: 'C. Palmer',
    position: 'CM',
    rating: 68,
    pace: 72,
    shooting: 62,
    passing: 70,
    dribbling: 65,
    defending: 68,
    physical: 75,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Retired',
    league: 'Premier League',
    imageUrl: sfImg(33),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(68),
    editions: ['custom'],
    isLegend: false,
    era: 'Legend',
  },
  {
    id: 'paqueta',
    name: 'Lucas Paquetá',
    shortName: 'L. Paquetá',
    position: 'CM',
    rating: 78,
    pace: 74,
    shooting: 74,
    passing: 79,
    dribbling: 82,
    defending: 56,
    physical: 70,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'West Ham United',
    league: 'Premier League',
    imageUrl: sfImg(230621),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('48'),
    baseValue: getBaseValue(78),
    editions: [...PL_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'rashica',
    name: 'Milot Rashica',
    shortName: 'M. Rashica',
    position: 'LW',
    rating: 73,
    pace: 88,
    shooting: 69,
    passing: 65,
    dribbling: 74,
    defending: 32,
    physical: 65,
    nationality: 'XK',
    nationalityFull: 'Kosovo',
    club: 'PAOK',
    league: 'Super League',
    imageUrl: sfImg(225801),
    flagUrl: flag('xk'),
    clubBadgeUrl: badge('225'),
    baseValue: getBaseValue(73),
    editions: ['custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'haland-alf',
    name: 'Alfie Haaland',
    shortName: 'A. Haaland',
    position: 'CDM',
    rating: 70,
    pace: 70,
    shooting: 56,
    passing: 66,
    dribbling: 60,
    defending: 76,
    physical: 79,
    nationality: 'NO',
    nationalityFull: 'Norway',
    club: 'Retired',
    league: 'Custom',
    imageUrl: sfImg(34),
    flagUrl: flag('no'),
    clubBadgeUrl: '',
    baseValue: getBaseValue(70),
    editions: ['custom'],
    isLegend: false,
    era: 'Legend',
  },
  {
    id: 'rodrygo',
    name: 'Rodrygo',
    shortName: 'Rodrygo',
    position: 'RW',
    rating: 85,
    pace: 88,
    shooting: 83,
    passing: 79,
    dribbling: 88,
    defending: 34,
    physical: 68,
    nationality: 'BR',
    nationalityFull: 'Brazil',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(250307),
    flagUrl: flag('br'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(85),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'valverde',
    name: 'Federico Valverde',
    shortName: 'F. Valverde',
    position: 'CDM',
    rating: 86,
    pace: 83,
    shooting: 79,
    passing: 81,
    dribbling: 82,
    defending: 81,
    physical: 87,
    nationality: 'UY',
    nationalityFull: 'Uruguay',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(238671),
    flagUrl: flag('uy'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(86),
    editions: [...LIGA_EDITIONS, 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'lunin',
    name: 'Andriy Lunin',
    shortName: 'A. Lunin',
    position: 'GK',
    rating: 83,
    pace: 55,
    shooting: 14,
    passing: 57,
    dribbling: 19,
    defending: 16,
    physical: 76,
    nationality: 'UA',
    nationalityFull: 'Ukraine',
    club: 'Real Madrid',
    league: 'La Liga',
    imageUrl: sfImg(242564),
    flagUrl: flag('ua'),
    clubBadgeUrl: badge('541'),
    baseValue: getBaseValue(83),
    editions: LIGA_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'correa',
    name: 'Joaquín Correa',
    shortName: 'J. Correa',
    position: 'ST',
    rating: 75,
    pace: 90,
    shooting: 72,
    passing: 63,
    dribbling: 76,
    defending: 30,
    physical: 73,
    nationality: 'AR',
    nationalityFull: 'Argentina',
    club: 'Marseille',
    league: 'Ligue 1',
    imageUrl: sfImg(225289),
    flagUrl: flag('ar'),
    clubBadgeUrl: badge('516'),
    baseValue: getBaseValue(75),
    editions: ['world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'greenwood',
    name: 'Mason Greenwood',
    shortName: 'M. Greenwood',
    position: 'RW',
    rating: 79,
    pace: 87,
    shooting: 79,
    passing: 71,
    dribbling: 80,
    defending: 36,
    physical: 68,
    nationality: 'GB-ENG',
    nationalityFull: 'England',
    club: 'Marseille',
    league: 'Ligue 1',
    imageUrl: sfImg(246469),
    flagUrl: flag('gb-eng'),
    clubBadgeUrl: badge('516'),
    baseValue: getBaseValue(79),
    editions: ['custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'milik',
    name: 'Arkadiusz Milik',
    shortName: 'A. Milik',
    position: 'ST',
    rating: 77,
    pace: 76,
    shooting: 80,
    passing: 67,
    dribbling: 72,
    defending: 36,
    physical: 77,
    nationality: 'PL',
    nationalityFull: 'Poland',
    club: 'Juventus',
    league: 'Serie A',
    imageUrl: sfImg(200389),
    flagUrl: flag('pl'),
    clubBadgeUrl: badge('496'),
    baseValue: getBaseValue(77),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'locatelli',
    name: 'Manuel Locatelli',
    shortName: 'M. Locatelli',
    position: 'CDM',
    rating: 81,
    pace: 63,
    shooting: 67,
    passing: 80,
    dribbling: 74,
    defending: 81,
    physical: 76,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Juventus',
    league: 'Serie A',
    imageUrl: sfImg(237896),
    flagUrl: flag('it'),
    clubBadgeUrl: badge('496'),
    baseValue: getBaseValue(81),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'dumfries',
    name: 'Denzel Dumfries',
    shortName: 'D. Dumfries',
    position: 'RB',
    rating: 82,
    pace: 84,
    shooting: 68,
    passing: 72,
    dribbling: 74,
    defending: 80,
    physical: 82,
    nationality: 'NL',
    nationalityFull: 'Netherlands',
    club: 'Inter Milan',
    league: 'Serie A',
    imageUrl: sfImg(236517),
    flagUrl: flag('nl'),
    clubBadgeUrl: badge('505'),
    baseValue: getBaseValue(82),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'bastoni',
    name: 'Alessandro Bastoni',
    shortName: 'A. Bastoni',
    position: 'CB',
    rating: 86,
    pace: 76,
    shooting: 51,
    passing: 79,
    dribbling: 68,
    defending: 86,
    physical: 83,
    nationality: 'IT',
    nationalityFull: 'Italy',
    club: 'Inter Milan',
    league: 'Serie A',
    imageUrl: sfImg(239921),
    flagUrl: flag('it'),
    clubBadgeUrl: badge('505'),
    baseValue: getBaseValue(86),
    editions: ['champions-league', 'world-cup', 'custom'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'diaz',
    name: 'Luis Díaz',
    shortName: 'L. Díaz',
    position: 'LW',
    rating: 87,
    pace: 93,
    shooting: 82,
    passing: 77,
    dribbling: 88,
    defending: 42,
    physical: 73,
    nationality: 'CO',
    nationalityFull: 'Colombia',
    club: 'Liverpool',
    league: 'Premier League',
    imageUrl: sfImg(247719),
    flagUrl: flag('co'),
    clubBadgeUrl: badge('40'),
    baseValue: getBaseValue(87),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'nunez',
    name: 'Darwin Núñez',
    shortName: 'D. Núñez',
    position: 'ST',
    rating: 85,
    pace: 95,
    shooting: 85,
    passing: 70,
    dribbling: 80,
    defending: 38,
    physical: 82,
    nationality: 'UY',
    nationalityFull: 'Uruguay',
    club: 'Liverpool',
    league: 'Premier League',
    imageUrl: sfImg(260865),
    flagUrl: flag('uy'),
    clubBadgeUrl: badge('40'),
    baseValue: getBaseValue(85),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'szoboszlai',
    name: 'Dominik Szoboszlai',
    shortName: 'D. Szoboszlai',
    position: 'CAM',
    rating: 84,
    pace: 80,
    shooting: 80,
    passing: 83,
    dribbling: 83,
    defending: 63,
    physical: 75,
    nationality: 'HU',
    nationalityFull: 'Hungary',
    club: 'Liverpool',
    league: 'Premier League',
    imageUrl: sfImg(257964),
    flagUrl: flag('hu'),
    clubBadgeUrl: badge('40'),
    baseValue: getBaseValue(84),
    editions: [...PL_EDITIONS, 'champions-league', 'world-cup'],
    isLegend: false,
    era: 'Modern',
  },
  {
    id: 'tsimikas',
    name: 'Konstantinos Tsimikas',
    shortName: 'K. Tsimikas',
    position: 'LB',
    rating: 79,
    pace: 78,
    shooting: 55,
    passing: 74,
    dribbling: 68,
    defending: 80,
    physical: 72,
    nationality: 'GR',
    nationalityFull: 'Greece',
    club: 'Liverpool',
    league: 'Premier League',
    imageUrl: sfImg(228745),
    flagUrl: flag('gr'),
    clubBadgeUrl: badge('40'),
    baseValue: getBaseValue(79),
    editions: PL_EDITIONS,
    isLegend: false,
    era: 'Modern',
  },
];

// Helper: filter players by edition
export function getPlayersForEdition(editionSlug: string): Player[] {
  return PLAYERS.filter((p) => p.editions.includes(editionSlug));
}

// Helper: get 11 positions in standard formation
export const STANDARD_POSITIONS = [
  'GK', 'LB', 'CB', 'CB', 'RB', 'CM', 'CM', 'CDM', 'LW', 'RW', 'ST',
] as const;

// Build position pool for an auction (one of each required position)
export const AUCTION_POSITIONS = [
  'GK', 'LB', 'CB', 'CB', 'RB', 'CDM', 'CM', 'CAM', 'LW', 'RW', 'ST',
] as const;
